
from bugbug import db, repository, bugzilla
import pprint

PATHS = [
"xpcom/base/CycleCollectedJSRuntime.cpp:1",
"startupcache/StartupCache.cpp:1",
"editor/libeditor/HTMLEditor.cpp:4",
"gfx/vr/VRManager.cpp:3",
"gfx/thebes/DeviceManagerDx.cpp:2",
"gfx/thebes/gfxPlatform.cpp:2",
"gfx/layers/apz/src/AsyncPanZoomController.cpp:10",
"gfx/layers/apz/src/PotentialCheckerboardDurationTracker.cpp:2",
"gfx/thebes/gfxUserFontSet.cpp:5",
"gfx/thebes/gfxDWriteFontList.cpp:9",
"gfx/layers/wr/WebRenderBridgeParent.cpp:4",
"gfx/layers/Layers.cpp:2",
"gfx/layers/ipc/ContentCompositorBridgeParent.cpp:1",
"gfx/layers/ipc/CompositorVsyncScheduler.cpp:1",
"gfx/layers/ipc/CompositorBridgeParent.cpp:18",
"gfx/layers/ipc/CompositorBridgeChild.cpp:3",
"gfx/thebes/gfxPlatformFontList.cpp:5",
"gfx/thebes/gfxFont.cpp:1",
"gfx/layers/d3d11/HelpersD3D11.h:1",
"gfx/thebes/gfxWindowsPlatform.cpp:2",
"gfx/src/DriverCrashGuard.cpp:1",
"gfx/thebes/gfxMacPlatformFontList.mm:1",
"gfx/vr/ipc/VRChild.cpp:1",
"gfx/vr/VRDisplayClient.cpp:1",
"gfx/gl/GLLibraryEGL.cpp:3",
"gfx/webrender_bindings/RenderThread.cpp:1",
"gfx/webrender_bindings/DCLayerTree.cpp:1",
"gfx/webrender_bindings/RenderCompositorANGLE.cpp:1",
"gfx/ipc/GPUParent.cpp:1",
"gfx/ipc/GPUChild.cpp:3",
"gfx/ipc/GPUProcessManager.cpp:3",
"toolkit/components/reputationservice/ApplicationReputation.cpp:3",
"toolkit/components/startup/nsAppStartup.cpp:1",
"toolkit/components/antitracking/AntiTrackingRedirectHeuristic.cpp:2",
"toolkit/components/antitracking/ContentBlocking.cpp:4",
"toolkit/components/antitracking/DynamicFpiRedirectHeuristic.cpp:2",
"toolkit/components/antitracking/ContentBlockingTelemetryService.cpp:1",
"toolkit/components/telemetry/core/Telemetry.cpp:2",
"toolkit/components/telemetry/core/TelemetryEvent.cpp:25",
"toolkit/components/telemetry/tests/gtest/TestHistograms.cpp:31",
"toolkit/components/telemetry/docs/collection/histograms.rst:1",
"toolkit/components/telemetry/docs/internals/tests.rst:1",
"toolkit/components/telemetry/geckoview/gtest/TestGeckoViewStreaming.cpp:12",
"toolkit/components/alerts/nsAlertsService.cpp:1",
"toolkit/components/places/nsNavHistory.cpp:1",
"toolkit/components/places/FaviconHelpers.cpp:7",
"toolkit/components/places/Database.cpp:1",
"toolkit/components/url-classifier/nsUrlClassifierUtils.cpp:2",
"toolkit/components/url-classifier/LookupCacheV4.cpp:1",
"toolkit/components/url-classifier/HashStore.cpp:1",
"toolkit/components/url-classifier/nsUrlClassifierStreamUpdater.cpp:6",
"toolkit/components/url-classifier/nsUrlClassifierDBService.cpp:4",
"toolkit/components/url-classifier/Classifier.cpp:1",
"toolkit/xre/nsXREDirProvider.cpp:2",
"toolkit/xre/nsAppRunner.cpp:6",
"ipc/glue/CrashReporterHost.cpp:1",
"ipc/chromium/src/base/pickle.cc:1",
"ipc/glue/MessageChannel.cpp:7",
"ipc/glue/GeckoChildProcessHost.cpp:2",
"accessible/base/Statistics.h:4",
"xpcom/base/MemoryTelemetry.cpp:2",
"xpcom/base/nsCycleCollector.cpp:2",
"dom/base/Document.cpp:22",
"dom/base/Selection.cpp:1",
"dom/base/nsGlobalWindowInner.cpp:5",
"dom/base/nsDOMNavigationTiming.cpp:12",
"dom/base/CCGCScheduler.h:1",
"dom/base/nsGlobalWindowOuter.cpp:1",
"dom/base/nsJSEnvironment.cpp:10",
"dom/base/nsFrameMessageManager.cpp:2",
"dom/ipc/ContentParent.cpp:9",
"dom/ipc/WindowGlobalParent.cpp:11",
"dom/performance/PerformanceTiming.cpp:1",
"dom/media/DecoderTraits.cpp:3",
"dom/media/webaudio/AudioDestinationNode.cpp:1",
"dom/media/MediaRecorder.cpp:1",
"dom/media/webrtc/libwebrtcglue/CodecStatistics.cpp:4",
"dom/media/webrtc/jsapi/PeerConnectionImpl.cpp:9",
"dom/media/webrtc/transport/transportlayerdtls.cpp:3",
"dom/media/MediaDecoderStateMachine.cpp:2",
"dom/media/MediaManager.cpp:4",
"dom/media/mp4/DecoderData.cpp:3",
"dom/media/eme/DetailedPromise.cpp:1",
"dom/media/CubebUtils.cpp:3",
"dom/media/MediaDecoder.cpp:1",
"dom/media/Benchmark.cpp:1",
"dom/media/encoder/TrackEncoder.cpp:2",
"dom/media/VideoFrameContainer.cpp:1",
"dom/media/platforms/wmf/DXVA2Manager.cpp:2",
"dom/media/platforms/wmf/WMFVideoMFTManager.cpp:1",
"dom/media/ogg/OggDemuxer.cpp:1",
"dom/media/gmp/GMPParent.cpp:1",
"dom/serviceworkers/ServiceWorkerPrivate.cpp:1",
"dom/serviceworkers/ServiceWorkerRegistrar.cpp:1",
"dom/serviceworkers/ServiceWorkerManager.cpp:3",
"dom/serviceworkers/ServiceWorkerUpdateJob.cpp:1",
"dom/quota/QuotaCommon.h:1",
"dom/quota/InitializationTypes.h:1",
"dom/quota/ActorsParent.cpp:3",
"dom/workers/WorkerRunnable.cpp:1",
"dom/workers/RuntimeService.cpp:6",
"dom/workers/WorkerPrivate.cpp:4",
"dom/system/windows/WindowsLocationProvider.cpp:2",
"dom/system/mac/CoreLocationLocationProvider.mm:2",
"dom/webauthn/U2FTokenManager.cpp:2",
"dom/geolocation/Geolocation.cpp:8",
"dom/canvas/CanvasRenderingContextHelper.cpp:10",
"dom/canvas/WebGLContext.cpp:3",
"dom/storage/LocalStorageCache.cpp:1",
"dom/script/ScriptLoader.cpp:1",
"dom/html/HTMLFormElement.cpp:2",
"dom/html/TextTrackManager.cpp:1",
"dom/html/TextControlState.cpp:4",
"dom/html/HTMLMediaElement.cpp:16",
"dom/html/HTMLInputElement.cpp:3",
"dom/xhr/XMLHttpRequestMainThread.cpp:1",
"dom/network/Connection.cpp:1",
"dom/xul/nsXULPrototypeCache.cpp:1",
"dom/security/nsContentSecurityUtils.cpp:1",
"dom/security/nsMixedContentBlocker.cpp:4",
"dom/security/nsHTTPSOnlyStreamListener.cpp:2",
"dom/plugins/ipc/PluginInstanceParent.cpp:1",
"dom/plugins/ipc/PluginModuleParent.cpp:1",
"dom/plugins/ipc/PluginHangUIParent.cpp:4",
"dom/indexedDB/IDBFactory.cpp:1",
"dom/vr/VREventObserver.cpp:2",
"dom/crypto/WebCryptoTask.cpp:27",
"devtools/shared/heapsnapshot/HeapSnapshot.cpp:4",
"extensions/auth/nsAuthGSSAPI.cpp:1",
"extensions/auth/nsAuthSSPI.cpp:1",
"extensions/auth/nsAuthSambaNTLM.cpp:1",
"extensions/permissions/PermissionManager.cpp:2",
"image/RasterImage.cpp:5",
"image/imgRequestProxy.cpp:1",
"storage/TelemetryVFS.cpp:3",
"storage/mozStorageConnection.cpp:1",
"netwerk/base/nsNetUtil.cpp:9",
"netwerk/cache/nsCacheService.cpp:2",
"netwerk/base/nsSocketTransport2.cpp:12",
"netwerk/base/NetworkConnectivityService.cpp:1",
"netwerk/base/nsUDPSocket.cpp:5",
"netwerk/base/Predictor.cpp:12",
"netwerk/base/nsIOService.cpp:1",
"netwerk/base/nsLoadGroup.cpp:18",
"netwerk/base/BackgroundFileSaver.cpp:1",
"netwerk/base/nsSocketTransportService2.cpp:6",
"netwerk/dns/TRR.cpp:3",
"netwerk/dns/nsHostResolver.cpp:25",
"netwerk/dns/TRRService.cpp:2",
"netwerk/cookie/CookiePersistentStorage.cpp:4",
"netwerk/cookie/CookieService.cpp:1",
"netwerk/cookie/CookieServiceChild.cpp:1",
"netwerk/system/win32/nsNotifyAddrListener.cpp:4",
"netwerk/system/mac/nsNetworkLinkService.mm:5",
"netwerk/system/netlink/NetlinkService.cpp:5",
"netwerk/protocol/http/Http3Session.cpp:8",
"netwerk/protocol/http/TRRServiceChannel.cpp:4",
"netwerk/protocol/http/InterceptedChannel.cpp:6",
"netwerk/protocol/http/Http2Session.cpp:12",
"netwerk/protocol/http/nsHttpHandler.cpp:7",
"netwerk/protocol/http/AlternateServices.cpp:3",
"netwerk/protocol/http/HttpBaseChannel.cpp:1",
"netwerk/protocol/http/nsHttpConnectionMgr.cpp:4",
"netwerk/protocol/http/nsHttpConnection.cpp:9",
"netwerk/protocol/http/nsHttpChannelAuthProvider.cpp:9",
"netwerk/protocol/http/HttpTrafficAnalyzer.cpp:2",
"netwerk/protocol/http/HttpChannelChild.cpp:1",
"netwerk/protocol/http/nsHttpTransaction.cpp:10",
"netwerk/protocol/http/Http2Stream.cpp:4",
"netwerk/protocol/http/nsHttpChannel.cpp:61",
"netwerk/protocol/http/HalfOpenSocket.cpp:2",
"netwerk/protocol/http/InterceptedHttpChannel.cpp:6",
"netwerk/protocol/http/Http3Stream.cpp:1",
"netwerk/protocol/http/Http2Compression.cpp:8",
"netwerk/protocol/http/HttpChannelParent.cpp:2",
"netwerk/cache2/OldWrappers.cpp:3",
"netwerk/cache2/CacheFileUtils.h:1",
"netwerk/cache2/CacheIOThread.cpp:1",
"netwerk/cache2/CacheFileMetadata.cpp:3",
"netwerk/cache2/CacheIndex.cpp:4",
"netwerk/cache2/CacheFileUtils.cpp:4",
"netwerk/cache2/CacheStorageService.cpp:3",
"netwerk/cache2/CacheFile.cpp:2",
"netwerk/cache2/CacheFileIOManager.cpp:1",
"netwerk/protocol/websocket/WebSocketChannel.cpp:1",
"layout/base/LayoutTelemetryTools.cpp:6",
"layout/base/PresShell.cpp:37",
"layout/base/nsLayoutUtils.cpp:2",
"layout/base/nsPresContext.cpp:2",
"layout/base/nsRefreshDriver.cpp:8",
"layout/generic/nsFrameSelection.cpp:1",
"layout/painting/nsDisplayList.cpp:4",
"layout/style/FontFaceSet.cpp:2",
"layout/style/nsFontFaceLoader.cpp:1",
"layout/style/GlobalStyleSheetCache.cpp:5",
"layout/xul/nsScrollbarButtonFrame.cpp:1",
"layout/xul/nsSliderFrame.cpp:3",
"security/manager/ssl/SSLServerCertVerification.cpp:40",
"security/manager/ssl/nsNSSCallbacks.cpp:16",
"security/manager/ssl/ContentSignatureVerifier.cpp:1",
"security/manager/ssl/nsCertOverrideService.cpp:1",
"security/manager/ssl/nsNSSComponent.cpp:2",
"security/manager/ssl/DataStorage.cpp:1",
"security/manager/ssl/nsNSSIOLayer.cpp:11",
"security/manager/ssl/nsNTLMAuthModule.cpp:1",
"security/sandbox/win/src/sandboxbroker/sandboxBroker.cpp:2",
"security/sandbox/linux/reporter/SandboxReporter.cpp:1",
"security/sandbox/win/src/remotesandboxbroker/RemoteSandboxBrokerParent.cpp:1",
"js/xpconnect/src/XPCJSContext.cpp:1",
"js/xpconnect/loader/ScriptPreloader.cpp:4",
"js/xpconnect/src/XPCJSRuntime.cpp:35",
"xpcom/threads/nsThread.cpp:1",
"widget/windows/nsWindow.cpp:1",
"widget/windows/nsLookAndFeel.cpp:1",
"widget/PrintBackgroundTask.h:2",
"widget/android/nsAppShell.cpp:1",
"widget/android/Telemetry.h:2",
"xpcom/ds/nsObserverService.cpp:1",
"docshell/base/nsDocShell.cpp:24",
"uriloader/preload/PreloaderBase.cpp:1",
]
# COMPONENT_COUNTS = collections.Counter(path_to_component[path.encode("utf-8")].tobytes().decode("utf-8") for path in PATHS if path.encode("utf-8") in path_to_component)


COMPONENT_COUNTS = {}
for path in PATHS:
  file_path = path.split(":")[0]
  count = int(path.split(":")[1])
  path_to_component = repository.get_component_mapping()
  try:
    component = path_to_component[file_path.encode("utf-8")].tobytes().decode("utf-8")
    if component in COMPONENT_COUNTS:
      COMPONENT_COUNTS[component] = COMPONENT_COUNTS[component] + count
    else:
      COMPONENT_COUNTS[component] = count
  except KeyError:
    print("error with " + file_path)

COMPONENT_COUNTS = dict(sorted(COMPONENT_COUNTS.items(), key=lambda item: -item[1]))


pp = pprint.PrettyPrinter(indent=4)

# pp.pprint(COMPONENT_COUNTS)

print(COMPONENT_COUNTS)
